import json
import os
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

import paho.mqtt.client as mqtt
import psycopg
from dateutil import parser as dateparser
from prometheus_client import Counter, start_http_server

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+psycopg://signalhub:signalhub@localhost:5432/signalhub",
).replace("postgresql+psycopg://", "postgresql://")
WINDOW_MINUTES = int(os.getenv("DETECTOR_WINDOW_MINUTES", "20"))
ERROR_THRESHOLD = int(os.getenv("DETECTOR_ERROR_THRESHOLD", "3"))

TOPIC_DEPLOY = "marketplace.ops.github.deployment.v1"
TOPIC_ERROR = "marketplace.ops.sentry.error_event.v1"
TOPIC_STORY = "marketplace.ops.incident.story.v1"

stories_generated_total = Counter("stories_generated_total", "Stories generated by detector")
correlations_detected_total = Counter("correlations_detected_total", "Deploy-error correlations detected")


@dataclass
class DeployContext:
    event_id: str
    repo: str
    env: str
    service: str
    release: str
    commit: str
    deploy_ref: str
    ts: datetime


def get_conn() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL)


def ensure_schema() -> None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS incidents (
                    id UUID PRIMARY KEY,
                    title TEXT NOT NULL,
                    severity TEXT NOT NULL,
                    status TEXT NOT NULL,
                    suspected_deploy_id UUID NULL,
                    confidence DOUBLE PRECISION NOT NULL,
                    summary TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );
                CREATE TABLE IF NOT EXISTS stories (
                    id UUID PRIMARY KEY,
                    incident_id UUID NOT NULL REFERENCES incidents(id),
                    story_text TEXT NOT NULL,
                    story_json JSONB NOT NULL,
                    ts TIMESTAMPTZ NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );
                """
            )
        conn.commit()


def parse_ts(value: str) -> datetime:
    return dateparser.parse(value).astimezone(UTC)


def create_incident_and_story(ctx: DeployContext, fingerprint: str, count: int, error_ts: datetime) -> dict:
    delta = max(int((error_ts - ctx.ts).total_seconds() // 60), 1)
    confidence = min(0.99, 0.5 + (count / max(ERROR_THRESHOLD, 1)) * 0.15)
    incident_id = str(uuid.uuid4())
    story_id = str(uuid.uuid4())
    story_text = (
        f"Deploy {ctx.commit} at {ctx.ts.isoformat().replace('+00:00', 'Z')} -> error {fingerprint} "
        f"rose to {count} within {delta}m. Suspected cause: {ctx.repo}@{ctx.commit}. "
        f"Confidence: {confidence:.2f}."
    )
    try:
        deploy_uuid = str(uuid.UUID(ctx.deploy_ref))
    except ValueError:
        deploy_uuid = str(uuid.uuid5(uuid.NAMESPACE_DNS, ctx.deploy_ref))

    incident = {
        "id": incident_id,
        "title": f"{ctx.service} errors spiked after deploy",
        "severity": "high" if count >= ERROR_THRESHOLD + 2 else "medium",
        "status": "open",
        "suspected_deploy_id": deploy_uuid,
        "confidence": confidence,
        "summary": story_text,
    }
    story_payload = {
        "incident_id": incident_id,
        "severity": incident["severity"],
        "count": count,
        "delta_minutes": delta,
        "story_text": story_text,
    }
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO incidents (id, title, severity, status, suspected_deploy_id, confidence, summary)
                VALUES (%s, %s, %s, %s, NULLIF(%s, '')::uuid, %s, %s)
                ON CONFLICT (id) DO NOTHING
                """,
                (
                    incident_id,
                    incident["title"],
                    incident["severity"],
                    incident["status"],
                    str(incident["suspected_deploy_id"]),
                    incident["confidence"],
                    incident["summary"],
                ),
            )
            cur.execute(
                """
                INSERT INTO stories (id, incident_id, story_text, story_json, ts)
                VALUES (%s, %s, %s, %s::jsonb, %s)
                """,
                (story_id, incident_id, story_text, json.dumps(story_payload), error_ts),
            )
        conn.commit()

    return {
        "event_id": story_id,
        "ts": error_ts.isoformat().replace("+00:00", "Z"),
        "source": "detector",
        "topic": TOPIC_STORY,
        "tags": {
            "repo": ctx.repo,
            "env": ctx.env,
            "service": ctx.service,
            "release": ctx.release,
            "deploy_id": ctx.deploy_ref,
            "commit": ctx.commit,
            "fingerprint": fingerprint,
        },
        "payload": story_payload,
    }


def main() -> None:
    ensure_schema()
    start_http_server(9103)
    deployments: dict[tuple[str, str, str], DeployContext] = {}
    fingerprint_counts: defaultdict[tuple[str, str], int] = defaultdict(int)
    generated_for: set[tuple[str, str]] = set()

    mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id="signalhub-detector")
    mqtt_client.username_pw_set(os.getenv("SOLACE_USERNAME", "admin"), os.getenv("SOLACE_PASSWORD", "admin"))

    def on_connect(client: mqtt.Client, _userdata: object, _flags: object, reason_code: object, _properties: object = None) -> None:
        if str(reason_code) == "Success":
            client.subscribe(TOPIC_DEPLOY, qos=1)
            client.subscribe(TOPIC_ERROR, qos=1)

    def on_message(client: mqtt.Client, _userdata: object, msg: mqtt.MQTTMessage) -> None:
        try:
            event = json.loads(msg.payload.decode("utf-8"))
            topic = event.get("topic")
            tags = event.get("tags", {})
            if topic == TOPIC_DEPLOY:
                key = (tags.get("env", "unknown"), tags.get("service", "unknown"), tags.get("release", ""))
                deployments[key] = DeployContext(
                    event_id=event.get("event_id", str(uuid.uuid4())),
                    repo=tags.get("repo", "unknown/repo"),
                    env=tags.get("env", "unknown"),
                    service=tags.get("service", "unknown"),
                    release=tags.get("release", ""),
                    commit=tags.get("commit", ""),
                    deploy_ref=tags.get("deploy_id", event.get("event_id", "")),
                    ts=parse_ts(event.get("ts", datetime.now(UTC).isoformat())),
                )
                return

            if topic != TOPIC_ERROR:
                return
            key = (tags.get("env", "unknown"), tags.get("service", "unknown"), tags.get("release", ""))
            ctx = deployments.get(key)
            if not ctx:
                return
            error_ts = parse_ts(event.get("ts", datetime.now(UTC).isoformat()))
            if error_ts > ctx.ts + timedelta(minutes=WINDOW_MINUTES):
                return
            fingerprint = str(tags.get("fingerprint", "unknown"))
            pair = (ctx.deploy_ref, fingerprint)
            fingerprint_counts[pair] += 1
            if fingerprint_counts[pair] < ERROR_THRESHOLD or pair in generated_for:
                return
            correlations_detected_total.inc()
            story_event = create_incident_and_story(ctx, fingerprint, fingerprint_counts[pair], error_ts)
            client.publish(TOPIC_STORY, json.dumps(story_event), qos=1)
            generated_for.add(pair)
            stories_generated_total.inc()
        except Exception as exc:  # noqa: BLE001
            print(json.dumps({"level": "error", "message": "detector failed", "error": str(exc)}))

    mqtt_client.on_connect = on_connect
    mqtt_client.on_message = on_message

    host = os.getenv("SOLACE_HOST", "localhost")
    port = int(os.getenv("SOLACE_PORT", "1883"))
    for attempt in range(1, 31):
        try:
            mqtt_client.connect(host, port, 60)
            break
        except (ConnectionRefusedError, OSError) as exc:
            print(json.dumps({"level": "warning", "message": f"Solace not ready ({attempt}/30)", "error": str(exc)}))
            time.sleep(3)
    else:
        raise ConnectionError(f"Could not connect to Solace at {host}:{port}")

    mqtt_client.loop_start()
    while True:
        time.sleep(2)


if __name__ == "__main__":
    main()
